### /planets
GET http://localhost:5000/planets HTTP/1.1

### /launches
GET http://localhost:5000/launches HTTP/1.1

### /launches
POST http://localhost:5000/launches HTTP/1.1
content-type: application/json

{ 
  "mission": "ZTM155",
  "rocket": "ZTM Experimental R1",
  "destination": "Kepler-168 f",
  "launchDate": "January 17, 2030",
  "target": "Kepler-1410 b"
}

### /launches
DELETE http://localhost:5000/launches/100 HTTP/1.1
