### /planets
GET http://localhost:5000/v1/planets HTTP/1.1

### /launches
GET http://localhost:5000/v1/launches HTTP/1.1

### /launches
POST http://localhost:5000/v1/launches HTTP/1.1
content-type: application/json

{ 
  "mission": "ZTM155",
  "rocket": "ZTM Experimental R1",
  "launchDate": "January 17, 2030",
  "target": "Kepler-1410 b"
}

### /launches
DELETE http://localhost:5000/v1/launches/102 HTTP/1.1
